integration: Install gel-cli

diff --git a/integration/linux/test/rockylinux-9/Dockerfile b/integration/linux/test/rockylinux-9/Dockerfile
--- a/integration/linux/test/rockylinux-9/Dockerfile
+++ b/integration/linux/test/rockylinux-9/Dockerfile
@@ -20,8 +20,8 @@ fi\n\
 \n\
 source /etc/os-release\n\
 \n\
-curl -fL https://packages.edgedb.com/rpm/edgedb-rhel.repo \\\n\
-    >/etc/yum.repos.d/edgedb.repo\n\
+curl -fL https://packages.geldata.com/rpm/gel-rhel.repo \\\n\
+    >/etc/yum.repos.d/gel.repo\n\
 \n\
 if [ "${VERSION_ID}" = "7" ]; then\n\
     # EPEL needed for jq on CentOS 7\n\
@@ -32,12 +32,21 @@ fi\n\
 try=1\n\
 while [ $try -le 30 ]; do\n\
     yum makecache \\\n\
-    && yum install --enablerepo=edgedb,edgedb-nightly --verbose -y edgedb-cli jq \\\n\
+    && yum install --enablerepo=gel,gel-nightly --verbose -y gel-cli jq \\\n\
     && break || true\n\
     try=$(( $try + 1 ))\n\
     echo "Retrying in 10 seconds (try #${try})"\n\
     sleep 10\n\
 done\n\
+\n\
+if ! type gel >/dev/null; then\n\
+    echo "could not install gel-cli" >&2\n\
+    exit $s\n\
+fi\n\
+\n\
+if ! type edgedb; then\n\
+    ln -s gel /usr/bin/edgedb\n\
+fi\n\
 \n\
 slot=\n\
 rpm=\n\
diff --git a/integration/linux/test/ubuntu-focal/Dockerfile b/integration/linux/test/ubuntu-focal/Dockerfile
--- a/integration/linux/test/ubuntu-focal/Dockerfile
+++ b/integration/linux/test/ubuntu-focal/Dockerfile
@@ -26,28 +26,32 @@ apt-get install -y curl gnupg apt-transport-https jq\n\
 \n\
 mkdir -p /usr/local/share/keyrings\n\
 curl --proto '\''=https'\'' --tlsv1.2 -sSf \\\n\
-    -o /usr/local/share/keyrings/edgedb-keyring.gpg \\\n\
-    https://packages.edgedb.com/keys/edgedb-keyring.gpg\n\
-echo deb [signed-by=/usr/local/share/keyrings/edgedb-keyring.gpg] \\\n\
-    https://packages.edgedb.com/apt "${dist}" main \\\n\
-    > "/etc/apt/sources.list.d/edgedb.list"\n\
+    -o /usr/local/share/keyrings/gel-keyring.gpg \\\n\
+    https://packages.geldata.com/keys/gel-keyring.gpg\n\
+echo deb [signed-by=/usr/local/share/keyrings/gel-keyring.gpg] \\\n\
+    https://packages.geldata.com/apt "${dist}" main \\\n\
+    > "/etc/apt/sources.list.d/gel.list"\n\
 if [ -n "${PKG_SUBDIST}" ]; then\n\
-    echo deb [signed-by=/usr/local/share/keyrings/edgedb-keyring.gpg] \\\n\
-        https://packages.edgedb.com/apt "${dist}" "${PKG_SUBDIST}" \\\n\
-        > "/etc/apt/sources.list.d/edgedb-${PKG_SUBDIST}.list"\n\
+    echo deb [signed-by=/usr/local/share/keyrings/gel-keyring.gpg] \\\n\
+        https://packages.geldata.com/apt "${dist}" "${PKG_SUBDIST}" \\\n\
+        > "/etc/apt/sources.list.d/gel-${PKG_SUBDIST}.list"\n\
 fi\n\
 \n\
 try=1\n\
 while [ $try -le 30 ]; do\n\
-    apt-get update && apt-get install -y edgedb-cli && break || true\n\
+    apt-get update && apt-get install -y gel-cli && break || true\n\
     try=$(( $try + 1 ))\n\
     echo "Retrying in 10 seconds (try #${try})" >&2\n\
     sleep 10\n\
 done\n\
 \n\
-if ! type edgedb >/dev/null; then\n\
-    echo "could not install edgedb-cli" >&2\n\
+if ! type gel >/dev/null; then\n\
+    echo "could not install gel-cli" >&2\n\
     exit $s\n\
+fi\n\
+\n\
+if ! type edgedb; then\n\
+    ln -s gel /usr/bin/edgedb\n\
 fi\n\
 \n\
 slot=\n\
